type BaseKey = string;
export type KeyId = BaseKey;

export const Key = {
  escape: "escape",
  esc: "esc",
  enter: "enter",
  return: "return",
  tab: "tab",
  space: "space",
  backspace: "backspace",
  delete: "delete",
  insert: "insert",
  clear: "clear",
  home: "home",
  end: "end",
  pageUp: "pageUp",
  pageDown: "pageDown",
  up: "up",
  down: "down",
  left: "left",
  right: "right",
  f1: "f1",
  f2: "f2",
  f3: "f3",
  f4: "f4",
  f5: "f5",
  f6: "f6",
  f7: "f7",
  f8: "f8",
  f9: "f9",
  f10: "f10",
  f11: "f11",
  f12: "f12",
  slash: "/",
  hyphen: "-",
  backslash: "\\",
  ctrl: <K extends BaseKey>(key: K) => `ctrl+${key}` as const,
  shift: <K extends BaseKey>(key: K) => `shift+${key}` as const,
  alt: <K extends BaseKey>(key: K) => `alt+${key}` as const,
  super: <K extends BaseKey>(key: K) => `super+${key}` as const,
  ctrlShift: <K extends BaseKey>(key: K) => `ctrl+shift+${key}` as const,
  shiftCtrl: <K extends BaseKey>(key: K) => `shift+ctrl+${key}` as const,
  ctrlAlt: <K extends BaseKey>(key: K) => `ctrl+alt+${key}` as const,
  ctrlSuper: <K extends BaseKey>(key: K) => `ctrl+super+${key}` as const,
} as const;
