import type { Keybinding, KeyId, KeybindingsConfig } from "@pit/tui";

export const KEYBINDING_NAME_MIGRATIONS = {
  cursorUp: "tui.editor.cursorUp", cursorDown: "tui.editor.cursorDown",
  cursorLeft: "tui.editor.cursorLeft", cursorRight: "tui.editor.cursorRight",
  cursorWordLeft: "tui.editor.cursorWordLeft", cursorWordRight: "tui.editor.cursorWordRight",
  cursorLineStart: "tui.editor.cursorLineStart", cursorLineEnd: "tui.editor.cursorLineEnd",
  jumpForward: "tui.editor.jumpForward", jumpBackward: "tui.editor.jumpBackward",
  pageUp: "tui.editor.pageUp", pageDown: "tui.editor.pageDown",
  deleteCharBackward: "tui.editor.deleteCharBackward", deleteCharForward: "tui.editor.deleteCharForward",
  deleteWordBackward: "tui.editor.deleteWordBackward", deleteWordForward: "tui.editor.deleteWordForward",
  deleteToLineStart: "tui.editor.deleteToLineStart", deleteToLineEnd: "tui.editor.deleteToLineEnd",
  yank: "tui.editor.yank", yankPop: "tui.editor.yankPop", undo: "tui.editor.undo",
  newLine: "tui.input.newLine", submit: "tui.input.submit", tab: "tui.input.tab", copy: "tui.input.copy",
  selectUp: "tui.select.up", selectDown: "tui.select.down",
  selectPageUp: "tui.select.pageUp", selectPageDown: "tui.select.pageDown",
  selectConfirm: "tui.select.confirm", selectCancel: "tui.select.cancel",
  interrupt: "app.interrupt", clear: "app.clear", exit: "app.exit", suspend: "app.suspend",
  cycleThinkingLevel: "app.thinking.cycle", cycleModelForward: "app.model.cycleForward",
  cycleModelBackward: "app.model.cycleBackward", selectModel: "app.model.select",
  expandTools: "app.tools.expand", toggleThinking: "app.thinking.toggle",
  toggleSessionNamedFilter: "app.session.toggleNamedFilter", externalEditor: "app.editor.external",
  followUp: "app.message.followUp", dequeue: "app.message.dequeue", pasteImage: "app.clipboard.pasteImage",
  newSession: "app.session.new", tree: "app.session.tree", fork: "app.session.fork", resume: "app.session.resume",
  treeFoldOrUp: "app.tree.foldOrUp", treeUnfoldOrDown: "app.tree.unfoldOrDown",
  treeEditLabel: "app.tree.editLabel", treeToggleLabelTimestamp: "app.tree.toggleLabelTimestamp",
  toggleSessionPath: "app.session.togglePath", toggleSessionSort: "app.session.toggleSort",
  renameSession: "app.session.rename", deleteSession: "app.session.delete",
  deleteSessionNoninvasive: "app.session.deleteNoninvasive",
} as const satisfies Record<string, Keybinding>;
